Final Project Biof309: Investigating deaths from Pneumonia and Influenza by state and region.

Author: Margaret Smith

Description: Influenza and Pnemonia are both respiratory infections that can lead to death. Influenza is a highly viral infection that we see spike in the winter time. Although treatable Influenza and Pnemonia are still deadly diseases. This project uses published data provided by the Center for Disease Control on deaths from Pneumonia and Influenza by state and region to exam trends of where in the US majority deaths are occuring.

In [2]:
import numpy as np

In [3]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

2) Uploading data and getting familiar Your data is required to be free and open to anyone. As such, you should have a URL which anyone can use to download your data:

https://healthdata.gov/dataset/deaths-pneumonia-and-influenza-pi-and-all-deaths-state-and-region-national-center-health

In [4]:
Death_data = pd.read_csv("https://data.cdc.gov/api/views/pp7x-dyj2/rows.csv?accessType=DOWNLOAD")

In [5]:
Death_data

,geoid,Region,State,age,season,MMWR Year/Week,Deaths from influenza,Deaths from pneumonia,Deaths from pneumonia and influenza,All Deaths,Pecent of deaths due to pneumonia or influenza,pecent complete
0,State,NaN,New Hampshire,All,2017-18,201805,NaN,NaN,28.0,286.0,9.790210,143.277643
1,State,NaN,New York City,All,2015-16,201629,NaN,NaN,64.0,972.0,6.584362,97.618498
2,State,NaN,Missouri,All,2009-10,201020,NaN,NaN,84.0,984.0,8.536585,93.231242
3,Region,3.0,NaN,All,2010-11,201134,0.0,280.0,280.0,4662.0,6.006006,92.565116
4,State,NaN,Kansas,All,2017-18,201820,NaN,NaN,19.0,496.0,3.830645,105.194581
...,...,...,...,...,...,...,...,...,...,...,...,...
32601,State,NaN,Vermont,All,2018-19,201909,NaN,NaN,10.0,115.0,8.695652,114.621584
32602,State,NaN,Pennsylvania,All,2017-18,201806,NaN,NaN,232.0,2896.0,8.011050,120.198668
32603,Region,7.0,NaN,All,2017-18,201822,1.0,141.0,142.0,2421.0,5.865345,102.902273
32604,State,NaN,Georgia,All,2017-18,201814,NaN,NaN,94.0,1640.0,5.731707,121.014408
32605,State,NaN,Rhode Island,All,2018-19,201901,NaN,NaN,17.0,190.0,8.947368,104.986252